### ISSUE TITLE
Bad fallback order

### ISSUE THREAD

**Issue by rdohms** [lcobucci/content-negotiation-middleware#16]
Given I have the following accepted formats:
- json, with mime `json/application`
- text with mimes: `text/plain`, and `text/plain;version=0.0.4`
When i send a request with `text/plain;version=0.0.5`
Then the response should be `text.plain`

What actually happens: we fall back on json.

**Comment by lcobucci** [comment]
As discussed IRL this happens due to attribute mismatch, detected by the [upstream library](https://github.com/willdurand/negotiation). It should be addressed there, if needed.

**Comment by lcobucci** [comment]
Related to https://github.com/willdurand/Negotiation/issues/66
