### ISSUE TITLE
It was not possible to parse your key, reason: error:0480006C:PEM routines::no start line

### ISSUE THREAD

**Issue by papac** [lcobucci/content-negotiation-middleware#639]
Good morning,

Can I get the configuration example using RS256 alg from:

```php
$builder = new Builder();
$builder->sign(new \Lcobucci\JWT\Signer\Rsa\Sha256(), new Key('signkey.pem'));
```

**Comment by lcobucci** [comment]
It looks like this belongs to `lcobucci/jwt` 😁

Would you please open an issue there with the full exception message?
